### PR TITLE
Vectorize drg rates

### LINKED ISSUE #48: Woo boy is the `get_rates_drg` function ever slow :)
Using the Galway DME/CH4 model with:

```
python -m cProfile __main__.py -m work/galway.cti --method DRG --targets CH4 --error 1e-4 --conditions work/input.txt
```

The input conditions are stoichometric methane at 1 Atm and 1000 and 1200K.

The reduction spends ~97% (287.821 / 297.121) percent of it's time calculating the DRG coefficients!!!!!!!!!

```
Testing for starting threshold value
Threshold     Species in Mech      Error
         45160355 function calls (45150236 primitive calls) in 302.849 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   ...
   1    0.000    0.000    0.000    0.000 drg.py:1(<module>)
   1    0.000    0.000  297.121  297.121 drg.py:142(run_drg)
   1    0.019    0.019    0.041    0.041 drg.py:19(trim_drg)
   1    0.000    0.000    0.041    0.041 drg.py:267(drg_loop_control)
   1  266.119  266.119  287.821  287.821 drg.py:336(get_rates_drg)
   1    0.000    0.000    0.000    0.000 drg.py:441(graph_search)
    ...
    1    3.126    3.126  300.247  300.247 pymars.py:14(pymars)
```

Various improvements:
- This method _really needs_ to be converted to updating of a numpy array for efficiency.  This is key.  String parsing is BAD.  Create a NxN numpy array (N = # of species) and use the species_index (this might be worth putting in a dict of gas.species_name->index) for indexing.
- Why the branched statement for `if reac_prod_rate > 0:` and `if reac_prod_rate < 0:`? Both branches do the same thing!

### PR DESCRIPTION
**Pull request by arghdos**
Should double check this for correctness, but it basically fixes #48

Bonus points if you optimize out the `sp_b` loop w/ `np.eigsum`

### CODE REVIEW

**Comment by xMestas** [comment]
Looks like this PR made the test related to DRG fail.  Try running pytest or check Travis to see the results.

**Comment by kyleniemeyer** [comment]
Yeah, it looks like this version changes the species that are identified in one of the tests.

**Comment by xMestas** [comment]
Yea.  Check out #50, a simple fix that makes it run much faster.

**Comment by kyleniemeyer** [comment]
I'm going to close this, since the idea was brought into the changes I made in #50 and which will be continued in the `refactor` branch.

**Pull request closed without merging**
